server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name hustlers.studio;

    include /etc/nginx/snippets/hustlers-projects/*.conf;

    location / {
        return 404;
    }
}