/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCityUsernameRouteImport } from './routes/api/public/city.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCityUsernameRoute = ApiPublicCityUsernameRouteImport.update({
  id: '/api/public/city/$username',
  path: '/api/public/city/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/city/$username': typeof ApiPublicCityUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/city/$username': typeof ApiPublicCityUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/city/$username': typeof ApiPublicCityUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/city/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/city/$username'
  id: '__root__' | '/' | '/api/public/city/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCityUsernameRoute: typeof ApiPublicCityUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/city/$username': {
      id: '/api/public/city/$username'
      path: '/api/public/city/$username'
      fullPath: '/api/public/city/$username'
      preLoaderRoute: typeof ApiPublicCityUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCityUsernameRoute: ApiPublicCityUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
